apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system # Patched later
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: controller-manager
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault # Added for better security posture
      containers:
      - name: manager
        # IMPORTANT: Replace with your built image name
        image: ghcr.io/konnektr-io/db-query-operator:latest
        imagePullPolicy: Always # Or IfNotPresent
        args:
        - "--leader-elect" # Enable leader election for production
        # Add other flags like --metrics-bind-address=:8080 if needed
        command:
        - /manager
        env:
        - name: GVK_PATTERN
          value: "v1/ConfigMap"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL" # Added for better security posture
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # Resources limits are recommended for production
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      terminationGracePeriodSeconds: 10