# Authentication Secrets Templates
# Copy this file and modify with your actual credentials

---
# Bearer Token Authentication
apiVersion: v1
kind: Secret
metadata:
  name: bearer-auth
  namespace: default
type: Opaque
stringData:
  token: "your-bearer-token-here"

---
# API Key Authentication
apiVersion: v1
kind: Secret
metadata:
  name: apikey-auth
  namespace: default
type: Opaque
stringData:
  apikey: "your-api-key-here"

---
# Basic Authentication
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: default
type: Opaque
stringData:
  username: "your-username"
  password: "your-password"

---
# Complex API with multiple auth methods
apiVersion: v1
kind: Secret
metadata:
  name: multi-auth
  namespace: default
type: Opaque
stringData:
  # Bearer token for main API
  bearer_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
  # API key for status updates
  status_api_key: "sk-1234567890abcdef"
  # Basic auth fallback
  username: "api_user"
  password: "secure_password_123"
