apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db-query-operator-system
resources:
  - ../crd/bases/konnektr.io_databasequeryresources.yaml
  - ../rbac/service_account.yaml
  - ../rbac/role.yaml
  - ../rbac/role_binding.yaml
  - ../manager/manager.yaml

namePrefix: db-query-operator-

images:
  - name: ghcr.io/konnektr-io/db-query-operator
    newName: ghcr.io/konnektr-io/db-query-operator
    newTag: latest

commonLabels:
  app.kubernetes.io/name: db-query-operator
  app.kubernetes.io/instance: db-query-operator
  app.kubernetes.io/managed-by: kustomize
